// AUTO-GENERATED by baluarte-build
// source: atoms
// uuid: 540f992622561935d2d33c48a0aa040c
// content_diff_hash: d581c45647b9613b6f59cb943e650af44111227ecb13d3f59030e31e85efbf20
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';

export interface CardPillStateProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
}

/**
 * CardPillState
 *
 * @description This component has an opacity on the background of 20%
 *
 * @baluarte uuid 540f992622561935d2d33c48a0aa040c
 */
export function CardPillState({ children, className = '', ...rest }: CardPillStateProps) {
  return (
    <div
      className={`flex flex-row items-center justify-center rounded-blte-40 border-blte-1 border-blte-c-79b9f3-a50 pt-blte-8 pb-blte-8 pl-blte-12 pr-blte-12 gap-blte-10 bg-blte-c-79b9f3-a20 text-blte-c-79b9f3 font-blte-pp-neue-montreal font-blte-w-400 text-blte-pp-neue-montreal-14 ${className}`.trim()}
      {...rest}
    >
      {children}
    </div>
  );
}
