// AUTO-GENERATED by baluarte-build
// source: atoms
// uuid: 540f992622561935d2d33c48a0aa040c
// content_diff_hash: d581c45647b9613b6f59cb943e650af44111227ecb13d3f59030e31e85efbf20
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { CardPillState } from './CardPillState';

const meta: Meta<typeof CardPillState> = {
  title: 'Atoms/card-pill-state',
  component: CardPillState,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    children: { control: 'text' },
  },
};
export default meta;

type Story = StoryObj<typeof CardPillState>;

export const Default: Story = {
  args: { children: 'In range' },
};
