// AUTO-GENERATED by baluarte-build
// source: components
// uuid: bbff77f0d3c839df329bf8097b851da4
// content_diff_hash: 1339a06b076529d91689dbb001fccfa81bda7f3350fb68a204b7486d8fe456ea
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import type { Meta, StoryObj } from '@storybook/react';
import { Pill } from './Pill';

const meta = {
  title: 'Components/Pill',
  component: Pill,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof Pill>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = { args: { priority: 'High' } };
export const High:    Story = { args: { priority: 'High' } };
export const Medium:  Story = { args: { priority: 'Medium' } };
export const Low:     Story = { args: { priority: 'Low' } };
