// AUTO-GENERATED by baluarte-build
// source: components
// uuid: bbff77f0d3c839df329bf8097b851da4
// content_diff_hash: 1339a06b076529d91689dbb001fccfa81bda7f3350fb68a204b7486d8fe456ea
// Edits will be overwritten on the next build. Edit the SQLite row instead.

export type PillPriority = 'High' | 'Medium' | 'Low';

const PRIORITY_CLASSES: Record<PillPriority, string> = {
  High:   'bg-blte-pill-high-bg text-blte-pill-high-text',
  Medium: 'bg-blte-pill-medium-bg text-blte-pill-medium-text',
  Low:    'bg-blte-pill-low-bg text-blte-pill-low-text',
};

export interface PillProps {
  label?: string;
  priority?: PillPriority;
}

/**
 * Pill
 *
 * @description Pills must never be full-width. They always shrink to fit their content (w-fit / inline-flex). Width is intrinsic, never set. A pill should also never grow beyond 160px wide — long labels truncate.
 *
 * @baluarte uuid bbff77f0d3c839df329bf8097b851da4
 */
export function Pill({ label, priority = 'High' }: PillProps) {
  const text = label ?? priority;
  return (
    <span
      className={`inline-flex w-fit max-w-[160px] truncate items-center pt-blte-2 pb-blte-2 pl-blte-10 pr-blte-10 rounded-blte-full text-blte-label font-blte-inter ${PRIORITY_CLASSES[priority]}`}
    >
      {text}
    </span>
  );
}
