// AUTO-GENERATED by baluarte-build
// source: atoms
// uuid: 543e70428c304bad16ea3269ac5831c0
// content_diff_hash: 79d201de697aa330cb5b85de02852d7bc1d636249ceca2405fa2bd02181455f9
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';

export interface AgePillProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
}

export function AgePill({ children, className = '', ...rest }: AgePillProps) {
  return (
    <div
      className={`flex flex-row items-center justify-center rounded-blte-30 pt-blte-8 pb-blte-8 pl-blte-12 pr-blte-12 gap-blte-13.57 shadow-blte-inset-3-white text-blte-c-000000 font-blte-feature-deck-trial font-blte-w-400 text-blte-feature-deck-trial-16 ${className}`.trim()}
      {...rest}
    >
      {children}
    </div>
  );
}
