// AUTO-GENERATED by baluarte-build
// source: atoms
// uuid: 543e70428c304bad16ea3269ac5831c0
// content_diff_hash: 79d201de697aa330cb5b85de02852d7bc1d636249ceca2405fa2bd02181455f9
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { AgePill } from './AgePill';

const meta: Meta<typeof AgePill> = {
  title: 'Atoms/age-pill',
  component: AgePill,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    children: { control: 'text' },
  },
};
export default meta;

type Story = StoryObj<typeof AgePill>;

export const Default: Story = {
  args: { children: '32' },
};
