// AUTO-GENERATED by baluarte-build-component
// registry_uuid: 6680380e-d08a-414a-9f9f-6c6bc56e223e
// components.uuid: 880e74a6-2807-46c7-af9b-5182629dcf51
// source_hash: bf16820a8ab0f40277a2f1d18e437e350c6257e9d116d072ea3fb4bdadd49773
// Edits will be overwritten when the source figma data changes. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react';
import { NavBarButton } from './NavBarButton';

const meta: Meta<typeof NavBarButton> = {
  title: 'Components/NavBarButton',
  component: NavBarButton,
  parameters: {
    backgrounds: { default: 'navbar-surface' },
  },
  argTypes: {
    label: { control: 'text' },
    active: { control: 'boolean' },
  },
};
export default meta;

type Story = StoryObj<typeof NavBarButton>;

export const Default: Story = {
  args: { label: 'Home', active: false },
};

export const Active: Story = {
  args: { label: 'My Health', active: true },
};
