// AUTO-GENERATED by baluarte-build-component
// registry_uuid: 6680380e-d08a-414a-9f9f-6c6bc56e223e
// components.uuid: 880e74a6-2807-46c7-af9b-5182629dcf51
// source_hash: bf16820a8ab0f40277a2f1d18e437e350c6257e9d116d072ea3fb4bdadd49773
// Edits will be overwritten when the source figma data changes. Edit the SQLite row instead.
import * as React from 'react';

export interface NavBarButtonProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onClick'> {
  label: string;
  active?: boolean;
  onPress?: () => void;
}

export function NavBarButton({
  label,
  active = false,
  onPress,
  className = '',
  ...rest
}: NavBarButtonProps) {
  const variantCls = active
    ? 'bg-navbar-button-active text-navbar-button-text-active rounded-[8px] px-[12px] py-[8px]'
    : 'bg-navbar-button-default text-navbar-button-text-default rounded-[11px] px-[15px] py-[10px]';

  return (
    <button
      type="button"
      onClick={onPress}
      aria-pressed={active}
      className={`inline-flex items-center justify-center gap-[10px] font-navbar-button-label text-navbar-button-label font-navbar-button-label ${variantCls} ${className}`}
      {...rest}
    >
      <span>{label}</span>
    </button>
  );
}
