// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 9766604a3d2dd171652675eb4e41941a
// content_diff_hash: 1cf386728102b53f85074e3fbdcb8dd5b36027034ee674f8e92334fd960b0eaa
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import type { Meta, StoryObj } from '@storybook/react';
import { ProductsSection } from './ProductsSection';

const meta = {
  title: 'Components/ProductsSection',
  component: ProductsSection,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof ProductsSection>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = { args: { cardCount: 5 } };
