// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 2d8238889827ed4f001d88b035d93353
// content_diff_hash: 1cf386728102b53f85074e3fbdcb8dd5b36027034ee674f8e92334fd960b0eaa
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import { SectionHeader } from '@/components/SectionHeader/SectionHeader';
import { Card } from '@/components/Card/Card';

export interface ProductsSectionProps {
  title?: string;
  cardCount?: number;
}

/**
 * ProductsSection
 *
 * @description Must keep a min-width of its current width (760px) and scroll horizontally when its content overflows. The inner row of cards never wraps — it scrolls. Since it is scrollable make sure to hide cards when overflowed.
 *
 * @baluarte uuid 2d8238889827ed4f001d88b035d93353
 */
export function ProductsSection({ title = 'Products', cardCount = 5 }: ProductsSectionProps) {
  return (
    <div className="flex flex-col gap-blte-16 pt-blte-20 pb-blte-20 pl-blte-20 pr-blte-20 min-w-[760px] overflow-x-hidden bg-blte-section rounded-blte-12">
      <SectionHeader title={title} />
      <div className="flex flex-row gap-blte-16 overflow-x-auto">
        {Array.from({ length: cardCount }).map((_, idx) => (
          <Card key={idx} media="Image" priority="High" />
        ))}
      </div>
    </div>
  );
}
