// AUTO-GENERATED by baluarte-build
// source: molecules
// uuid: 9cf544da07cc9a46a6001a803b1e9804
// content_diff_hash: a9eeb0e31b86de8d9c73ad7d965b7202d793cef9300a36c5911f5d72bd991eed
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';
import { CardPillState } from '../../atoms/CardPillState/CardPillState';

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  pillLabel?: React.ReactNode;
  children?: React.ReactNode;
}

export function Card({ pillLabel = 'In range', children, className = '', ...rest }: CardProps) {
  return (
    <div
      className={`flex flex-col rounded-blte-10 pt-blte-16 pb-blte-16 pl-blte-16 pr-blte-16 gap-blte-17 bg-blte-c-202020 ${className}`.trim()}
      {...rest}
    >
      <CardPillState>{pillLabel}</CardPillState>
      {children}
    </div>
  );
}
