// AUTO-GENERATED by baluarte-build
// source: molecules
// uuid: 9cf544da07cc9a46a6001a803b1e9804
// content_diff_hash: a9eeb0e31b86de8d9c73ad7d965b7202d793cef9300a36c5911f5d72bd991eed
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Card } from './Card';

const meta: Meta<typeof Card> = {
  title: 'Molecules/card',
  component: Card,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    pillLabel: { control: 'text' },
  },
};
export default meta;

type Story = StoryObj<typeof Card>;

export const Default: Story = {
  args: { pillLabel: 'In range' },
};
