// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 587a2bc07f1b1ecbab1fa3292bd3acc9
// content_diff_hash: db386d817ef08f60d72fa064d86eef73f7486007d16897d7276153f30bc37c52
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Button, type ButtonState } from './Button';

const meta = {
  title: 'Components/Button',
  component: Button,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default:  Story = { args: { state: 'stale' } };
export const Stale:    Story = { args: { state: 'stale' } };
export const Hover:    Story = { args: { state: 'hover' } };
export const Disabled: Story = { args: { state: 'disabled' } };
export const Focus:    Story = { args: { state: 'focus' } };

export const Interactive: Story = {
  render: () => {
    const [state, setState] = useState<ButtonState>('stale');
    return (
      <Button
        state={state}
        onMouseEnter={() => setState('hover')}
        onMouseLeave={() => setState('stale')}
        onFocus={() => setState('focus')}
        onBlur={() => setState('stale')}
      />
    );
  },
};
