// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 587a2bc07f1b1ecbab1fa3292bd3acc9
// content_diff_hash: db386d817ef08f60d72fa064d86eef73f7486007d16897d7276153f30bc37c52
// Edits will be overwritten on the next build. Edit the SQLite row instead.

export type ButtonState = 'stale' | 'hover' | 'disabled' | 'focus';

const STATE_CLASSES: Record<ButtonState, string> = {
  stale:    'bg-blte-button-default text-blte-text-default',
  hover:    'bg-blte-button-hover text-blte-text-default',
  disabled: 'bg-blte-button-disabled text-blte-text-disabled cursor-not-allowed',
  focus:    'bg-blte-button-default text-blte-text-default ring-blte-3 ring-blte-focus',
};

export interface ButtonProps {
  label?: string;
  state?: ButtonState;
  onMouseEnter?: () => void;
  onMouseLeave?: () => void;
  onFocus?: () => void;
  onBlur?: () => void;
  onClick?: () => void;
}

/**
 * Button
 *
 * @description Any button instance should fill the width of its container (w-full), but never grow beyond the width of the button rendered inside a Card (~304px after the card's 8/8 horizontal padding). Encode as full-width with a max-width cap.
 *
 * @baluarte uuid 587a2bc07f1b1ecbab1fa3292bd3acc9
 */
export function Button({
  label = 'Button',
  state = 'stale',
  onMouseEnter,
  onMouseLeave,
  onFocus,
  onBlur,
  onClick,
}: ButtonProps) {
  return (
    <button
      type="button"
      disabled={state === 'disabled'}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onFocus={onFocus}
      onBlur={onBlur}
      onClick={onClick}
      className={`w-full max-w-[304px] inline-flex items-center justify-center px-4 h-[35px] rounded-blte-8 text-blte-button font-blte-inter ${STATE_CLASSES[state]}`}
    >
      {label}
    </button>
  );
}
