// AUTO-GENERATED by baluarte-build
// source: layouts
// uuid: b58066f0b1fb000ebf666f9002362de4
// content_diff_hash: 2cf86145c90fb69b5cfaba9b7b89838e2eb84e98bff9a19e03fd2a894ceabc08
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';
import { NavBar } from '../../molecules/NavBar/NavBar';

export interface MyHealthProps extends React.HTMLAttributes<HTMLElement> {
  active?: string;
}

const DEFAULT_ITEMS = [
  { label: 'Home' },
  { label: 'My Health' },
  { label: 'Care' },
  { label: 'Products' },
  { label: 'Groups' },
];

export function MyHealth({ active = 'My Health', className = '', ...rest }: MyHealthProps) {
  return (
    <section
      className={`min-h-screen bg-blte-c-131313 ${className}`.trim()}
      {...rest}
    >
      <NavBar items={DEFAULT_ITEMS} active={active} />
    </section>
  );
}
