// AUTO-GENERATED by baluarte-build
// source: layouts
// uuid: b58066f0b1fb000ebf666f9002362de4
// content_diff_hash: 2cf86145c90fb69b5cfaba9b7b89838e2eb84e98bff9a19e03fd2a894ceabc08
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { MyHealth } from './MyHealth';

const meta: Meta<typeof MyHealth> = {
  title: 'Layouts/my-health',
  component: MyHealth,
  parameters: { layout: 'fullscreen' },
  decorators: [
    (Story) => (
      <div className="min-h-screen w-screen m-0 p-0">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    active: {
      control: 'select',
      options: ['Home', 'My Health', 'Care', 'Products', 'Groups'],
    },
  },
};
export default meta;

type Story = StoryObj<typeof MyHealth>;

export const Default: Story = {
  args: { active: 'My Health' },
};
