// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 2449854ddb3f14cd748fabd80a8a76a9
// content_diff_hash: e90a0a5f189384f8d571341652c4bfc650740f515788895fb07c822a534c0c89
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import type { Meta, StoryObj } from '@storybook/react';
import { ButtonLink } from './ButtonLink';

const meta = {
  title: 'Components/ButtonLink',
  component: ButtonLink,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof ButtonLink>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = { args: {} };
