// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 2449854ddb3f14cd748fabd80a8a76a9
// content_diff_hash: e90a0a5f189384f8d571341652c4bfc650740f515788895fb07c822a534c0c89
// Edits will be overwritten on the next build. Edit the SQLite row instead.

export interface ButtonLinkProps {
  label?: string;
  onClick?: () => void;
}

export function ButtonLink({ label = 'View all', onClick }: ButtonLinkProps) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="inline-flex items-center pt-blte-4 pb-blte-4 gap-blte-6 text-blte-label font-blte-inter text-blte-text-default"
    >
      <span>{label}</span>
      <svg
        width="16"
        height="16"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        <path
          d="M6 4l4 4-4 4"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </button>
  );
}
