// AUTO-GENERATED by baluarte-build
// source: layouts
// uuid: bbed11fb7d4bbe5b226b0cac57648644
// content_diff_hash: 9ee5584ba7c9d57fc5df2642039988399a3b6098e9b3c33a19bb554de8471b49
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';
import { NavBar } from '../../molecules/NavBar/NavBar';

export interface BrainHealthProps extends React.HTMLAttributes<HTMLElement> {
  active?: string;
}

const DEFAULT_ITEMS = [
  { label: 'Home' },
  { label: 'My Health' },
  { label: 'Care' },
  { label: 'Products' },
  { label: 'Groups' },
];

export function BrainHealth({ active = 'My Health', className = '', ...rest }: BrainHealthProps) {
  return (
    <section
      className={`min-h-screen bg-blte-c-131313 ${className}`.trim()}
      {...rest}
    >
      <NavBar items={DEFAULT_ITEMS} active={active} />
    </section>
  );
}
