// AUTO-GENERATED by baluarte-build
// source: layouts
// uuid: bbed11fb7d4bbe5b226b0cac57648644
// content_diff_hash: 9ee5584ba7c9d57fc5df2642039988399a3b6098e9b3c33a19bb554de8471b49
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { BrainHealth } from './BrainHealth';

const meta: Meta<typeof BrainHealth> = {
  title: 'Layouts/Brain Health',
  component: BrainHealth,
  parameters: { layout: 'fullscreen' },
  decorators: [
    (Story) => (
      <div className="min-h-screen w-screen m-0 p-0">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    active: {
      control: 'select',
      options: ['Home', 'My Health', 'Care', 'Products', 'Groups'],
    },
  },
};
export default meta;

type Story = StoryObj<typeof BrainHealth>;

export const Default: Story = {
  args: { active: 'My Health' },
};
