// AUTO-GENERATED by baluarte-build
// source: atoms
// uuid: 7339b1d36720ca08cad8e6186ae96dd8
// content_diff_hash: 256789047236274a687d972ae8d5e826a019d3a0055ffd3a1b9e5516691a4003
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';

export type NavButtonState = 'stale' | 'active';

export interface NavButtonProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'children'> {
  label: string;
  state?: NavButtonState;
}

const STATE_CLASSES: Record<NavButtonState, string> = {
  stale: 'flex flex-row items-center justify-center rounded-blte-11 pt-blte-10 pb-blte-10 pl-blte-15 pr-blte-15 gap-blte-10 bg-blte-c-212121 text-blte-c-edf3fa font-blte-sequel-sans font-blte-w-305 text-blte-sequel-sans-14',
  active: 'flex flex-row items-center justify-center rounded-blte-11 pt-blte-10 pb-blte-10 pl-blte-15 pr-blte-15 gap-blte-10 bg-blte-c-f3ef81 text-blte-c-000000 font-blte-sequel-sans font-blte-w-305 text-blte-sequel-sans-14',
};

/**
 * NavButton
 *
 * @description When hovered this button should change from cursor to pointer
 *
 * @baluarte uuid 7339b1d36720ca08cad8e6186ae96dd8
 */
export function NavButton({ label, state = 'stale', className = '', ...rest }: NavButtonProps) {
  return (
    <button
      type="button"
      aria-pressed={state === 'active'}
      className={`${STATE_CLASSES[state]} cursor-pointer ${className}`.trim()}
      {...rest}
    >
      <span>{label}</span>
    </button>
  );
}
