// AUTO-GENERATED by baluarte-build
// source: atoms
// uuid: 7339b1d36720ca08cad8e6186ae96dd8
// content_diff_hash: 256789047236274a687d972ae8d5e826a019d3a0055ffd3a1b9e5516691a4003
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { fn } from 'storybook/test';
import { useState } from 'react';
import { NavButton } from './NavButton';

const meta: Meta<typeof NavButton> = {
  title: 'Atoms/nav-button',
  component: NavButton,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    label: { control: 'text' },
    state: { control: 'select', options: ['stale', 'active'] },
  },
};
export default meta;

type Story = StoryObj<typeof NavButton>;

export const Default: Story = {
  args: { label: 'Home', state: 'stale' },
};

export const Active: Story = {
  args: { label: 'My Health', state: 'active' },
};

// Honors the entity description: a click toggles the active state via useState
// and fires `onClick` so the Storybook Actions panel logs the navigation.
export const Interactive: Story = {
  args: {
    label: "Rodrigo",
    onClick: fn(),
    state: "active"
  },
  render: (args) => {
    const [active, setActive] = useState(false);
    return (
      <NavButton
        {...args}
        state={active ? 'active' : 'stale'}
        onClick={(e) => {
          setActive((v) => !v);
          args.onClick?.(e);
        }}
      />
    );
  },
};
