// AUTO-GENERATED by baluarte-build
// source: molecules
// uuid: bd84e2bbbb6019ca9841386ae9e52f0e
// content_diff_hash: f3013cb15b1a3ecf2d3ef30a6bab87f29c4d65e515bea4a094249f9e2cb3fa01
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import * as React from 'react';
import { NavButton } from '../../atoms/NavButton/NavButton';

export interface NavBarItem {
  label: string;
  onPress?: () => void;
}

export interface NavBarProps extends Omit<React.HTMLAttributes<HTMLElement>, 'onChange'> {
  items: NavBarItem[];
  active?: string;
  onChange?: (label: string) => void;
}

/**
 * NavBar
 *
 * @description This component should not be full width, the width is determined by the amount of children buttons it has, some ideas to tackle this may include inline-flex or a max-width property
 *
 * @baluarte uuid bd84e2bbbb6019ca9841386ae9e52f0e
 */
export function NavBar({ items, active, onChange, className = '', ...rest }: NavBarProps) {
  return (
    <nav
      aria-label="Primary"
      className={`inline-flex flex-row items-center justify-center rounded-blte-10 pt-blte-4 pb-blte-4 pl-blte-9 pr-blte-9 gap-blte-13 bg-blte-c-212121 ${className}`.trim()}
      {...rest}
    >
      {items.map((item) => (
        <NavButton
          key={item.label}
          label={item.label}
          state={item.label === active ? 'active' : 'stale'}
          onClick={() => {
            item.onPress?.();
            onChange?.(item.label);
          }}
        />
      ))}
    </nav>
  );
}
