// AUTO-GENERATED by baluarte-build
// source: molecules
// uuid: bd84e2bbbb6019ca9841386ae9e52f0e
// content_diff_hash: f3013cb15b1a3ecf2d3ef30a6bab87f29c4d65e515bea4a094249f9e2cb3fa01
// Edits will be overwritten on the next build. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { NavBar } from './NavBar';

const items = [
  { label: 'Home' },
  { label: 'My Health' },
  { label: 'Care' },
  { label: 'Products' },
  { label: 'Groups' },
];

const meta: Meta<typeof NavBar> = {
  title: 'Molecules/nav-bar',
  component: NavBar,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
  argTypes: {
    active: {
      control: 'select',
      options: items.map((i) => i.label),
    },
  },
};
export default meta;

type Story = StoryObj<typeof NavBar>;

export const Default: Story = {
  args: { items, active: 'My Health' },
};
