// AUTO-GENERATED by baluarte-build — do not hand-edit.
// Source: SQLite properties. Re-run /baluarte-build to regenerate.
//
// Every theme key carries the `blte-` namespace prefix so the resulting
// Tailwind classes (bg-blte-*, text-blte-*, pt-blte-*, rounded-blte-*,
// shadow-blte-*) cannot collide with Tailwind built-ins. Tailwind built-in
// utilities (flex flex-row, items-center, justify-center, overflow-x-hidden,
// truncate, max-w-[Npx], etc.) are NOT prefixed and NOT registered here —
// they are ambient utilities (see baluarte-build §8.invariant).

export const baluarteTheme = {
  colors: {
    'blte-button-default':   '#E5DD1F', // @baluarte uuid=b179820d56ed0af7806af0480e258e7f
    'blte-button-hover':     '#7A7510', // @baluarte uuid=11fd5a4461e6f819d35ba3506ad29416
    'blte-button-disabled':  '#F5F1C7', // @baluarte uuid=751aa4fdfdf8d97c4bfa5792ef2461b3
    'blte-text-default':     '#0A0A0A', // @baluarte uuid=3fa15cdc57d39bc10468f9e1210ad162
    'blte-text-disabled':    '#B8B8B8', // @baluarte uuid=7257314c63b24ac928689e21aa39d03b
    'blte-pill-high-bg':     '#FDE2E2', // @baluarte uuid=862b395d30b03a0e85768df7dc534d5c
    'blte-pill-medium-bg':   '#FEF6C7', // @baluarte uuid=a08b6e240eba7fab0631b64305efcd19
    'blte-pill-low-bg':      '#D1FADF', // @baluarte uuid=82edb93a54a6677250a6eb9b559b7fe5
    'blte-pill-high-text':   '#B42318', // @baluarte uuid=3544248ac18d2feba3d8e55f876f1f17
    'blte-pill-medium-text': '#8A6E0F', // @baluarte uuid=22bf4b2c5830869944028f434108d978
    'blte-pill-low-text':    '#067647', // @baluarte uuid=eb1028a0aad93e42f2111ef857f35b82
    'blte-section-header':   '#374151', // @baluarte uuid=c9f0fe0e0847e5cdbf82d0b62b36ef46
    'blte-section':          '#F7F7FA', // @baluarte uuid=905c4bb8047525edd2d8dcf15bc91629
    'blte-card':             '#FFFFFF', // @baluarte uuid=4b78d589be03145533c12f5b91935e4f
    'blte-focus':            '#7A7510', // @baluarte uuid=30eb56e89d1be8725e3a0df8197454ac
  },
  spacing: {
    'blte-2':  '2px',  // @baluarte uuid=d282fcd1fb8f4b56ffe3e8a852cf2450
    'blte-4':  '4px',  // @baluarte uuid=4743fa3a5c6572d0ee0e351584138f47
    'blte-6':  '6px',  // @baluarte uuid=c832d50657064d89770a5c981fedb23f
    'blte-8':  '8px',  // @baluarte uuid=2285147931f65260db9402e43f324649
    'blte-10': '10px', // @baluarte uuid=f3a9a0e0f3b9d45ab20ae44045c9b751
    'blte-16': '16px', // @baluarte uuid=799ba1fbc65b5ec132925e98119e8c0d
    'blte-20': '20px', // @baluarte uuid=394a98a0b0e0b8459b1fe68d71ef9980
    'blte-24': '24px', // @baluarte uuid=9c8877c1d400cd638628a228e8549c9f
    'blte-40': '40px', // @baluarte uuid=5502f8ccf5cf57580aef4e01dda47a74
    'blte-60': '60px', // @baluarte uuid=dade4ba3c8351471e2553db1697379bd
  },
  borderRadius: {
    'blte-8':    '8px',    // @baluarte uuid=757e981a4f6f66e2b79bd72c731bae6c
    'blte-12':   '12px',   // @baluarte uuid=cacbe3c578e0d01e4f65addb0db32ef7
    'blte-full': '9999px', // @baluarte uuid=b520c26edd37ccaa711c9315e33b5376
  },
  borderWidth: {
    'blte-3': '3px', // @baluarte uuid=dc44c47e106df402d148ce490a4f5156
  },
  boxShadow: {
    'blte-card': '0px 4px 16px 0px rgba(0, 0, 0, 0.08)', // @baluarte uuid=30b966996adf063adcbea6a67b62fea8
  },
  fontFamily: {
    'blte-inter': ['Inter', 'sans-serif'],
  },
  fontSize: {
    'blte-button':         ['12px', { lineHeight: '1.21em', fontWeight: '700' }],                          // @baluarte uuid=58d21e6f9d2010db0df261610698b25e
    'blte-label':          ['12px', { lineHeight: '1.33em', fontWeight: '600' }],                          // @baluarte uuid=00672e51466082d97cef23a8c9a8cd24
    'blte-section-header': ['12px', { lineHeight: '1.33em', fontWeight: '600', letterSpacing: '0.08em' }], // @baluarte uuid=57aab8ccd4832cb4bf1e98c6125ea5b0
    'blte-heading':        ['20px', { lineHeight: '1.4em',  fontWeight: '700' }],                          // @baluarte uuid=46ae646f6bd04c089584ce2c9f196323
    'blte-body':           ['14px', { lineHeight: '1.43em', fontWeight: '400' }],                          // @baluarte uuid=cd4c47af6db6b1fd8d59a66773be9385
  },
} as const;
