// AUTO-GENERATED by baluarte-build — do not hand-edit.
// Source: SQLite properties. Re-run /baluarte-build to regenerate.
//
// Empty stub. The next /baluarte-build run will repopulate this file
// from the current registry (one entry per row in `properties`).

export const baluarteTheme = {
  colors: {},
  spacing: {},
  borderRadius: {},
  borderWidth: {},
  fontFamily: {},
  fontSize: {},
  fontWeight: {},
  lineHeight: {},
  letterSpacing: {},
  boxShadow: {},
  opacity: {},
  _other: {},
} as const;
