// AUTO-GENERATED by baluarte-build — do not hand-edit.
// Source: SQLite properties. Re-run /baluarte-build to regenerate.
//
// Every theme key carries the `blte-` namespace prefix so the resulting
// Tailwind classes (bg-blte-*, text-blte-*, pt-blte-*, rounded-blte-*,
// shadow-blte-*, font-blte-*, leading-blte-*, tracking-blte-*) cannot
// collide with Tailwind's built-in palette / spacing / radius / shadow
// names. Tailwind built-ins (`flex flex-row`, `items-center`,
// `justify-center`) are NOT prefixed and not registered here.

export const baluarteTheme = {
  colors: {
    'blte-actions-idle': '#000000', /* TODO: alias unresolved (Figma Variable) */ // @baluarte uuid=ae3fc16d8e52445413096802300581b5
    'blte-blue-300': '#79b9f3', // @baluarte uuid=8e92150edf8b84fb924553862d81ea58
    'blte-blue-500': '#3a98ed', // @baluarte uuid=095d393d849801010a46d045cb3f83c9
    'blte-blue-700': '#1e64aa', // @baluarte uuid=4d93f7c5905b7324aff2f1c64ae23945
    'blte-c-000000': '#000000', // @baluarte uuid=6d3f780bd38e45ea06b0671c74b30ab1
    'blte-c-131313': '#131313', // @baluarte uuid=d795dcd56c9ad3f23761c499a44cd089
    'blte-c-212121': '#212121', // @baluarte uuid=a7eb4dfbf2cea71db3af4d0163ab5ba2
    'blte-c-edf3fa': '#edf3fa', // @baluarte uuid=923dc3a2a42554bc5a02a583ad37102d
    'blte-c-f3ef81': '#f3ef81', // @baluarte uuid=ba6ec98cdf95000ebd0367064d6885f3
    'blte-core-grey-500': '#e0e0e0', // @baluarte uuid=d007b1d535ff3eb62a1cc921ab6e511a
    'blte-foundation-obsidian': '#031016', // @baluarte uuid=b1ad7ab65161f5b1ff7e10e802da959e
    'blte-foundation-pure': '#ffffff', // @baluarte uuid=74537fec636e8a1bc7eb74de71acb21f
    'blte-foundation-sky': '#edf3fa', // @baluarte uuid=f2c711045492800bf99826cd5bf556c0
    'blte-green-500': '#62a442', // @baluarte uuid=29510156d65680e9efe1f0cb0e41446b
    'blte-green-700': '#3b6a25', // @baluarte uuid=efa2103bcc580e74c360bd7258915b07
    'blte-neutral-0': '#ffffff', // @baluarte uuid=acf8fce851a11a5cbb9cd9ed885f6499
    'blte-neutral-200': '#d5d4d3', // @baluarte uuid=e53bb30d13e85014df58b10880da76af
    'blte-red-500': '#ec4141', // @baluarte uuid=3966ef2cd3866a2363f3af584f396cb1
    'blte-red-700': '#a93535', // @baluarte uuid=942b0f592cb666ca1728ca30d26629f9
    'blte-supporting-current': '#66f3ff', // @baluarte uuid=45a6ba7ca647d1ccd4e6a278afb050ad
    'blte-supporting-renewal': '#d9a6f9', // @baluarte uuid=70ad48617a7881475b19c767d6e00233
    'blte-surfaces-in-range-primary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=7d0d2d30bc8c811efa80a0db74aaf994
    'blte-surfaces-optimal-primary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=e33967c5855d2e8d5ccbbfb935c68e65
    'blte-surfaces-out-of-range-primary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=7a6df9cb758cfbda94644998be46dd62
    'blte-surfaces-primary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=2e370e5d1b361d1f67c166b25c6bcc13
    'blte-surfaces-secondary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=0708e109143c327410f058df1dcdefc5
    'blte-surfaces-surface-inverse': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=b29df62053dfbb1bb550ca1148437f23
    'blte-surfaces-tertiary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=d26dc618c3acc90d36cd79485eb3054a
    'blte-text-in-range': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=cd1944ec0bf0c20e2edb318108423602
    'blte-text-optimal': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=f89c27c0a4500eefbd4e3244f71822ae
    'blte-text-out-of-range': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=fc45fd349a6ad495ce5d5ca82a668f77
    'blte-text-primary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=92c82346a904a52d5eacf77f36cbafc3
    'blte-text-secondary': '#000000', /* TODO: alias unresolved */ // @baluarte uuid=703ac48d75170735a00c248ffea26be8
    'blte-yellow-200': '#f3ef81', // @baluarte uuid=3cada64af1bb9bbcb4af60bebd298e7d
  },
  spacing: {
    'blte-4': '4px',     // @baluarte uuids=116f9cada99c196ad78d0616fec49262,e22a97c64605d7f426f2a137e9d6e379
    'blte-8': '8px',     // @baluarte uuids=a41096f44cc01668bf75b13eb0783dbb,e39ca8c997365b8436b8005a2af53023
    'blte-9': '9px',     // @baluarte uuids=6bd26a6cc9eb1693a83eff4b4c7fadc5,5cc8e7c98553b77f73112fa867a94ac7
    'blte-10': '10px',   // @baluarte uuids=8a8f6306f1f63e58cce6002475886616,5d540caae65b2d9e4467e592b7dba818,f321894727edd66e740ab1085c73cfc2
    'blte-12': '12px',   // @baluarte uuids=07baeb947d4cc209319f240c837ffbd0,2745427ca30530488d9272505662cc24
    'blte-13': '13px',   // @baluarte uuids=44ce107f992d0b514ea5719d557a6acf
    'blte-13.57': '13.571428298950195px', // @baluarte uuid=893c9777ea1fcf0218fe08b436a1f3f8
    'blte-15': '15px',   // @baluarte uuids=55bd05e9bad9f16fc2ca0f690f36c1f3,b3d9ef6832ac1287e79ed0aee15ededd
  },
  borderRadius: {
    'blte-10': '10px', // @baluarte uuid=e501de1d44a876ce981cb04a9404d670
    'blte-11': '11px', // @baluarte uuid=835277b6d3373dfa2a4682cda82d4e10
    'blte-24': '24px', // @baluarte uuid=5773aeaf18cf6e1f7e6a9b96ca197cab
    'blte-30': '30px', // @baluarte uuid=f37681649379c62de281065f25529a07
  },
  fontFamily: {
    'blte-feature-deck-trial': ['Feature Deck Trial', 'sans-serif'], // @baluarte uuid=757490fdf4a00c830b62bd7e05e1fb75
    'blte-sequel-sans': ['Sequel Sans', 'sans-serif'], // @baluarte uuid=324d37263c0e42a139edbab745668f92
  },
  fontSize: {
    'blte-feature-deck-trial-16': ['16px', { lineHeight: '15.199999809265137px', letterSpacing: '-0.32px' }], // @baluarte uuid=757490fdf4a00c830b62bd7e05e1fb75
    'blte-sequel-sans-14': ['14px', { lineHeight: '16.51999855041504px', letterSpacing: '-0.14px' }], // @baluarte uuid=324d37263c0e42a139edbab745668f92
  },
  fontWeight: {
    'blte-w-305': '305', // @baluarte uuid=324d37263c0e42a139edbab745668f92
    'blte-w-400': '400', // @baluarte uuid=757490fdf4a00c830b62bd7e05e1fb75
  },
  lineHeight: {},
  boxShadow: {
    'blte-inset-3-white': 'inset 0 0 3px 0 #ffffff', // @baluarte uuid=26174bd8921581456ea7670d1966d898
  },
  _other: {
    // Flex-row → `flex flex-row` (Tailwind built-in) // @baluarte uuid=74c27535efd1f947573241fed2e20879
    // Flex-items-center → `items-center` (Tailwind built-in) // @baluarte uuid=039657fe3559aaf5139eed46e432b721
    // Flex-justify-center → `justify-center` (Tailwind built-in) // @baluarte uuid=c57fe862b1154fd5150ff00e03e8ba6c
  },
} as const;
