// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 1216f0d1b0a67c3bd5df3f0b927d23a3
// content_diff_hash: acb79c8c1031d444b4ab38ad3794ffc56a43d7d8901984eb77f90208a69b9fca
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import type { Meta, StoryObj } from '@storybook/react';
import { SectionHeader } from './SectionHeader';

const meta = {
  title: 'Components/SectionHeader',
  component: SectionHeader,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof SectionHeader>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = { args: {} };
