// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 1216f0d1b0a67c3bd5df3f0b927d23a3
// content_diff_hash: acb79c8c1031d444b4ab38ad3794ffc56a43d7d8901984eb77f90208a69b9fca
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import { ButtonLink } from '@/components/ButtonLink/ButtonLink';

export interface SectionHeaderProps {
  title?: string;
  linkLabel?: string;
  onLinkClick?: () => void;
}

/**
 * SectionHeader
 *
 * @description section-header should always be full width, constrained to the parent component's width.
 *
 * @baluarte uuid 1216f0d1b0a67c3bd5df3f0b927d23a3
 */
export function SectionHeader({
  title = 'Products',
  linkLabel = 'View all',
  onLinkClick,
}: SectionHeaderProps) {
  return (
    <div className="flex flex-row justify-between items-center pt-blte-4 pb-blte-4 w-full text-blte-section-header font-blte-inter">
      <h2 className="text-blte-section-header uppercase tracking-[0.08em]">{title}</h2>
      <ButtonLink label={linkLabel} onClick={onLinkClick} />
    </div>
  );
}
