// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 097c65254f2e843099b40e4a3443e3db
// content_diff_hash: 5791c5207748e414615830db70588d02aa88dee28ec732a4c3cda83aba7ef1b8
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import { SectionHeader } from '@/components/SectionHeader/SectionHeader';
import { Card } from '@/components/Card/Card';

export interface ProductsSectionTextProps {
  title?: string;
  cardCount?: number;
}

/**
 * ProductsSectionText
 *
 * @description Must keep a min-width of its current width (760px) and scroll horizontally when its content overflows. The inner row of cards never wraps — it scrolls.
 *
 * @baluarte uuid 097c65254f2e843099b40e4a3443e3db
 */
export function ProductsSectionText({ title = 'Products', cardCount = 5 }: ProductsSectionTextProps) {
  return (
    <div className="flex flex-col gap-blte-16 pt-blte-20 pb-blte-20 pl-blte-20 pr-blte-20 min-w-[760px] bg-blte-section rounded-blte-12">
      <SectionHeader title={title} />
      <div className="flex flex-row gap-blte-16 overflow-x-auto">
        {Array.from({ length: cardCount }).map((_, idx) => (
          <Card key={idx} media="None" priority="High" />
        ))}
      </div>
    </div>
  );
}
