// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 097c65254f2e843099b40e4a3443e3db
// content_diff_hash: 5791c5207748e414615830db70588d02aa88dee28ec732a4c3cda83aba7ef1b8
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import type { Meta, StoryObj } from '@storybook/react';
import { ProductsSectionText } from './ProductsSectionText';

const meta = {
  title: 'Components/ProductsSectionText',
  component: ProductsSectionText,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof ProductsSectionText>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = { args: { cardCount: 5 } };
