// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 39840e0cf12b91d6a4fbad23da144781
// content_diff_hash: 2094e3133e8972b65c3ac4d29020beec89699d083d607294cb5cc7e842b51bbd
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import { Pill, type PillPriority } from '@/components/Pill/Pill';
import { Button } from '@/components/Button/Button';

export type CardMedia = 'Image' | 'None';

export interface CardProps {
  media?: CardMedia;
  priority?: PillPriority;
  heading?: string;
  body?: string;
  ctaLabel?: string;
}

export function Card({
  media = 'Image',
  priority = 'High',
  heading = 'Card heading goes here',
  body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  ctaLabel = 'Button',
}: CardProps) {
  return (
    <div className="flex flex-col w-[320px] min-w-[320px] bg-blte-card rounded-blte-8 shadow-blte-card overflow-hidden">
      {media === 'Image' ? (
        <div
          className="relative h-[250px] w-full"
          style={{ background: 'linear-gradient(90deg, rgba(140,166,217,1) 0%, rgba(64,89,140,1) 100%)' }}
        >
          <div className="absolute top-blte-10 left-blte-10">
            <Pill priority={priority} />
          </div>
        </div>
      ) : null}
      <div className="flex flex-col gap-blte-16 pt-blte-24 pb-blte-24 pl-blte-16 pr-blte-16">
        {media === 'None' ? <Pill priority={priority} /> : null}
        <h3 className="text-blte-heading font-blte-inter text-blte-text-default">{heading}</h3>
        <p className="text-blte-body font-blte-inter text-blte-text-disabled">{body}</p>
      </div>
      <div className="flex flex-row items-center justify-center pl-blte-8 pr-blte-8 pb-blte-8">
        <Button label={ctaLabel} />
      </div>
    </div>
  );
}
