// AUTO-GENERATED by baluarte-build
// source: components
// uuid: 39840e0cf12b91d6a4fbad23da144781
// content_diff_hash: 2094e3133e8972b65c3ac4d29020beec89699d083d607294cb5cc7e842b51bbd
// Edits will be overwritten on the next build. Edit the SQLite row instead.

import type { Meta, StoryObj } from '@storybook/react';
import { Card } from './Card';

const meta = {
  title: 'Components/Card',
  component: Card,
  parameters: { layout: 'centered' },
  decorators: [
    (Story) => (
      <div className="flex min-h-screen w-screen items-center justify-center">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof Card>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = { args: { media: 'Image' } };
export const Image:   Story = { args: { media: 'Image' } };
export const None:    Story = { args: { media: 'None' } };
