// AUTO-GENERATED by baluarte-build-component
// registry_uuid: c94f7093-d830-4546-8401-9ddd55b2c6c3
// components.uuid: b179fa20-1ae5-404c-9929-76a90f00678e
// source_hash: 747581efa786926fa340dac3e9d8d8c617fbcb9669a201bc5c8c0db67455ff76
// Edits will be overwritten when the source figma data changes. Edit the SQLite row instead.
import * as React from 'react';
import { NavBarButton } from '../NavBarButton/NavBarButton';

export interface NavBarItem {
  label: string;
  onPress?: () => void;
}

export interface NavBarProps extends Omit<React.HTMLAttributes<HTMLElement>, 'onChange'> {
  items: NavBarItem[];
  active?: string;
  onChange?: (label: string) => void;
}

export function NavBar({
  items,
  active,
  onChange,
  className = '',
  ...rest
}: NavBarProps) {
  return (
    <nav
      aria-label="Primary"
      className={`inline-flex flex-row items-center gap-[13px] px-[9px] py-[4px] rounded-[10px] bg-navbar-surface ${className}`}
      {...rest}
    >
      {items.map((item) => (
        <NavBarButton
          key={item.label}
          label={item.label}
          active={item.label === active}
          onPress={() => {
            item.onPress?.();
            onChange?.(item.label);
          }}
        />
      ))}
    </nav>
  );
}
