// AUTO-GENERATED by baluarte-build-component
// registry_uuid: c94f7093-d830-4546-8401-9ddd55b2c6c3
// components.uuid: b179fa20-1ae5-404c-9929-76a90f00678e
// source_hash: 747581efa786926fa340dac3e9d8d8c617fbcb9669a201bc5c8c0db67455ff76
// Edits will be overwritten when the source figma data changes. Edit the SQLite row instead.
import type { Meta, StoryObj } from '@storybook/react';
import { NavBar } from './NavBar';

const items = [
  { label: 'Home' },
  { label: 'My Health' },
  { label: 'Care' },
  { label: 'Products' },
  { label: 'Groups' },
];

const meta: Meta<typeof NavBar> = {
  title: 'Components/NavBar',
  component: NavBar,
  argTypes: {
    active: {
      control: 'select',
      options: items.map((i) => i.label),
    },
  },
};
export default meta;

type Story = StoryObj<typeof NavBar>;

export const Default: Story = {
  args: { items, active: 'My Health' },
};

export const HomeActive: Story = {
  args: { items, active: 'Home' },
};
